services:
  document:
    # image: ghcr.io/kyundae-kim/docmesh-doc:v0.1.3
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .release/.env
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - net
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=docmesh-infra_net"
      - "traefik.http.routers.document.rule=PathPrefix(`/dms`)"
      - "traefik.http.routers.document.entrypoints=web"
      - "traefik.http.services.document.loadbalancer.server.port=8000"

  postgres:
    image: postgres:17.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docmesh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  net:
    external: true
    name: docmesh-infra_net
  backend:
    driver: bridge
 